# Generated by Django 3.1.2 on 2021-12-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='location',
            name='cp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.sherpauser'),
        ),
    ]
